# The success of sudoku 10c in looking for different solutions is encouraging.
# It took it 0.2 seconds to find all the 12 solutions of a sudoku puzzle with
# sereval clue removed (also found some clue to be useless).
#
# So, what we'll do now is figure out an argithrim to make a move with
# a given board.
#
# Imaginea tree of all possiblity, with the top branches being a completed
# Sudoku. The tree has many branches terminated at a certain point.
# I'm somewhat bored when writing this, so I'll inculde a graph just for fun.
#
# P is a uncompleted Sudoku, and S is completed. T mean rules were broken
# T right after a branch is ingorned
#   0 1 2 3 4 5 6 7
# A P┬P┬P┬P┬P─P─P-S
# B  │ │ │ ├P─P-P-T
# C  │ │ │ └P-P-P-T
# D  │ │ ├P┬P─P-T
# E  │ │ │ └P-P-P-T
# F  │ │ └P─P-P-P-S
# G  │ ├P┬P┬P─P─P-S
# H  │ │ │ ├P─T
# I  │ │ │ └P-P-P-S
# J  │ │ ├P┬P─P-T
# K  │ │ │ └P-P-P-T
# L  │ │ └P─P-P-P-S
# M  │ ├P┬P─P┬P─P─S
# N  │ │ │   └P─P-S
# O  │ │ └P─P─P─P─S
# P  │ └P─P┬P─P─P─T
# Q  │     └P┬P─P─T
# R  │       └P─P─T
# S  └P-P┬P─P─P─P─T
# T      └P─P─P─P─S
# Simbols: ┼│├┴─┬┤┘┐┌└
#
# If there is infinte calculating power, the result is set.
# In the graph, the best move is S1!
# However, that require calculating if all possible move has only one move.
# Asuming the graph is known, to calculate best move:
#
# Attempt 1:
# Imagine assigning the value 2 to all S.
# If someone has this board feeded to him, ! would guarteen a win.
# Now trace it back one layer.
# If two S merged(which is to say it branched into at least two S),
# Set this to 1, at which saying ! after one solution would be a win
# Else set that node to 2 as well
# Then continue to trace it back
# If there are no merge, remain the same#Wrong, figure it out.
# Else if there is a 2 in merger, set it to 1
# Else, if all
#
# Note: Don't work when you are sleepy
# The previous example doesn't work because the tree is acturally
# generated by my program, while a real one has loop, and the best
# move can be quite different
#
# So what we'll be doing would be: First, use the few brain cells
# you have left to figure out the winning stratage when you know every
# solutions.
# Second, check if the technic can be used even when only tree is known,
# if it work: Third: Try reducing the completeness of the tree needed.
